version: '3.9'

services:
  redis:
    image: redis/redis-stack:latest

    # TODO - set password and test connection in browser
    # command: redis-server --requirepass hibech

    ports:
      - 6379:6379
      - 8001:8001